### ISSUE TITLE
Use `latest` tag for Docker image

### ISSUE THREAD

**Issue by nwithan8** [fu/fass#1]
Someone mentioned this project on a Reddit thread the other week, and I noticed there wasn't an Unraid template for it, so I made one (should be available on the Unraid Community Apps store within a few hours). To make maintaining the template easier, can you please use the `latest` tag for the latest version of each Docker container you make (in addition to the usual explicit version number), so that users only have to target `latest` rather than needing to know the version number.

**Comment by ghzgod** [comment]
Came here for this, please add the latest tag.  Only zerealfu/fass:0.1.0 works currently.

**Comment by fu** [comment]
Thanks for pointing out @ghzgod - added latest tag to github actions and is now available on dockerhub.
